[workspace]
members = [
    ".",        # kernel crate
    "user"      # user programs crate
]
[package]
name = "xv6"
version = "0.1.0"
edition = "2021"
autobins = false

[lib]
name = "kernel"
path = "src/lib.rs"  # Use lib.rs instead of main.rs
crate-type = ["staticlib"]  # Build a static library (.a)

[dependencies]
modular-bitfield = "0.11.2"

[profile.release]
panic="abort"
debug = true
opt-level = "s"    # Optimize for size
codegen-units = 1  # Fewer units for better cross-function inlining
lto = true        # Disabled Link-time optimization