pub const NPROC: usize = 64; // maximum number of processes
pub const KSTACKSIZE: usize = 4096; // size of per-process kernel stack (unused in p3)
pub const NCPU: usize = 8; // maximum number of CPUs
pub const MAXOPBLOCKS: usize = 10; // max # of blocks any FS op writes
pub const MAXARG: usize = 32; // max exec arguments
pub const NOFILE: usize = 16; // open files per process
pub const NFILE: usize = 100; // open files per system
pub const NINODE: usize = 50; // maximum number of active i-nodes
pub const NDEV: usize = 10; // maximum major device number
pub const ROOTDEV: u32 = 1; // device number of file system root disk
pub const LOGSIZE: usize = MAXOPBLOCKS * 3; // max data blocks in on-disk log
pub const CONSOLE: usize = 1; // console device number
